[package]
name = "screenland"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.14.0", features = ["image", "advanced"] }
iced_core = {version = "0.14.0", features = ["serde"]}
bytemuck = "1.24.0"
glam = { version = "0.25.0", features = ["bytemuck", "serde"] }
iced_aw = "0.13.0"
grim-rs = "0.1.1"
tokio = { version = "1.49.0", features = ["full"] }
image = "0.25.9"
chrono = "0.4.43"
clap = { version = "4.5.54", features = ["derive"] }
native-dialog = "0.9.6"
arboard = { version = "3.6.1", features = ["wayland-data-control"] }
serde = "1.0.228"
serde_yaml = "0.9.34"
directories = "6.0.0"
iced_font_awesome = "0.4.1"
sugar = "0.2.0"
heck = "0.5"
iced_helper = {git = "https://github.com/Andrewkoro105/iced_helper.git"}
iced_layershell = "0.16.0"
strum = { version = "0.28", features = ["derive"] }
tracing-subscriber = "0.3.23"
tracing = "0.1.44"
xdg = "3.0.0"
#iced_helper = {path = "../iced_helper"}